name: bionmed
version: 1.2.9+29
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get: 4.6.5
  google_fonts: 3.0.1
  carousel_slider: 4.2.1
  intl_phone_number_input: 0.7.1
  dotted_decoration: 2.0.0
  dio: 4.0.6
  get_storage: 2.0.3
  platform_device_id: 1.0.1
  loading_overlay: 0.3.0
  flutter_spinkit: 5.1.0
  lottie: 2.1.0
  flutter_screenutil: 5.6.0
  image_picker: ^0.8.6+4
  http: 0.13.5
  flutter_rating_bar: 4.0.1
  zego_uikit_prebuilt_call: ^3.12.0
#  zego_zim: ^2.5.0+1
  zego_uikit_signaling_plugin: ^2.2.1
  flutter_countdown_timer: 4.1.0
  # firebase_core: 2.4.1
  flutter_local_notifications: 13.0.0
  # firebase_messaging: 14.2.1
  auto_size_text: 3.0.0
  google_maps_flutter: 2.2.3
  geolocator: 9.0.2
  geocoding: 2.0.5
  search_map_location: 0.0.6
  search_map_place_updated: 0.0.4
  assets_audio_player: ^3.0.6
  cached_network_image: ^3.2.1
  flutter_callkit_incoming: ^2.0.0
  awesome_notifications: ^0.7.4+1
  url_launcher: ^6.1.10
  maps_launcher: ^2.2.0
  currency_text_input_formatter: ^2.1.2
  permission_handler: 10.4.3
  zego_zimkit: ^1.7.0
  flutter_email_sender: ^6.0.1
  file_picker: ^5.2.5
  open_file: ^3.3.2
  pinput: ^2.2.20
  flutter: 
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/logo-doctor.png
  ios: true

flutter: 
  assets: 
    - assets/
    - assets/icon/
    - assets/icon/icon_hospital/
    - assets/images/
    - assets/json/
    - assets/pdf/
  uses-material-design: true

