// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCeWCoVtjIOOdLnWaK0xE-wGp7dOD1gQc',
    appId: '1:409575069878:web:b27a3ecd60c658acbb2e17',
    messagingSenderId: '409575069878',
    projectId: 'bionmed-754cc',
    authDomain: 'bionmed-754cc.firebaseapp.com',
    storageBucket: 'bionmed-754cc.appspot.com',
    measurementId: 'G-4NNK2Q17B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPGrdYPs9xIQLKmhE48axs-LSvZO2YP4',
    appId: '1:409575069878:android:ab6c7ff2c5bf3589bb2e17',
    messagingSenderId: '409575069878',
    projectId: 'bionmed-754cc',
    storageBucket: 'bionmed-754cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT8D-oqSkLkLyP5Km2bOfMc7LSaOktyZU',
    appId: '1:409575069878:ios:0125e57f31df4098bb2e17',
    messagingSenderId: '409575069878',
    projectId: 'bionmed-754cc',
    storageBucket: 'bionmed-754cc.appspot.com',
    iosClientId: '409575069878-l97jldk3cm215vcnli1s7jcp79t53vmp.apps.googleusercontent.com',
    iosBundleId: 'com.bionmed.bionmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT8D-oqSkLkLyP5Km2bOfMc7LSaOktyZU',
    appId: '1:409575069878:ios:0125e57f31df4098bb2e17',
    messagingSenderId: '409575069878',
    projectId: 'bionmed-754cc',
    storageBucket: 'bionmed-754cc.appspot.com',
    iosClientId: '409575069878-l97jldk3cm215vcnli1s7jcp79t53vmp.apps.googleusercontent.com',
    iosBundleId: 'com.bionmed.bionmed',
  );
}
