// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB9iw9PjMm3oiGjy50XUiL4jPmVGn1BFls',
//     appId: '1:1067667317386:web:073a517f62083f7127c373',
//     messagingSenderId: '1067667317386',
//     projectId: 'bionmed-f09dc',
//     authDomain: 'bionmed-f09dc.firebaseapp.com',
//     storageBucket: 'bionmed-f09dc.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAUXcJrdeM-FmZIJDCwOWIwbvEwHQDpamk',
//     appId: '1:1067667317386:android:11a153c7f8758ad727c373',
//     messagingSenderId: '1067667317386',
//     projectId: 'bionmed-f09dc',
//     storageBucket: 'bionmed-f09dc.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAn6jSvkj7jHgB5EA07HY2r_PkZ0oNjGvA',
//     appId: '1:1067667317386:ios:fee13df2a631573c27c373',
//     messagingSenderId: '1067667317386',
//     projectId: 'bionmed-f09dc',
//     storageBucket: 'bionmed-f09dc.appspot.com',
//     iosClientId: '1067667317386-l0r3qcmichbrg9vro56s25vua43pae5q.apps.googleusercontent.com',
//     iosBundleId: 'com.bionmed.bionmed',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAn6jSvkj7jHgB5EA07HY2r_PkZ0oNjGvA',
//     appId: '1:1067667317386:ios:fee13df2a631573c27c373',
//     messagingSenderId: '1067667317386',
//     projectId: 'bionmed-f09dc',
//     storageBucket: 'bionmed-f09dc.appspot.com',
//     iosClientId: '1067667317386-l0r3qcmichbrg9vro56s25vua43pae5q.apps.googleusercontent.com',
//     iosBundleId: 'com.bionmed.bionmed',
//   );
// }
